Update lint.yml to fail on any error detected by shellcheck

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -36,7 +36,7 @@ jobs:
           verbose: true
           failure-threshold: error
   shellcheck:
-    name: 'ShellCheck (annotations only)'
+    name: 'ShellCheck (fail on error)'
     runs-on: ubuntu-20.04
     steps:
       - name: Checkout
@@ -48,7 +48,17 @@ jobs:
           action: add
           linters: gcc
       - name: Run shellcheck
-        run: for file in $(find . -name *.sh); do /usr/local/bin/shellcheck --format=gcc $file && :; done; true
+        run: |
+          run_shellcheck() {
+            for arg in "$@"; do
+              SHELLCHECK_OUT=$(/usr/local/bin/shellcheck --format=gcc "$arg") && :;
+              echo "$SHELLCHECK_OUT"
+              # fail on error
+              echo "$SHELLCHECK_OUT" | grep -q -v -E '^.*:[[:digit:]]:[[:digit:]]:\s+(?:fatal\s+)?(error):\s+.*$'
+            done
+          }
+          export -f run_shellcheck
+          find . -name '*.sh' -exec bash -c 'set -e; run_shellcheck "$@"' {} +
       - uses: liskin/gh-problem-matcher-wrap@v2
         with:
           action: remove
